DROP TABLE Student1;
DROP TABLE Library1;
DROP TABLE Emp1;
DROP TABLE Project1;
DROP TABLE Assign1;

CREATE TABLE Student1
(
S_Id INTEGER PRIMARY KEY,
S_Name VARCHAR2(20)
);

CREATE TABLE Library1
(
Issn_No INTEGER PRIMARY KEY,
S_Id INTEGER,
B_Name varchar2(20)
);

CREATE TABLE Emp1
(
Emp_Id INTEGER,
EName VARCHAR2(20),
Address VARCHAR2(20),
DOJ DATE,
Dept VARCHAR2(20)
);

CREATE TABLE Project1
(
Pro_Id INTEGER,
PName VARCHAR2(20),
Start_Date DATE,
End_Date DATE
);

CREATE TABLE Assign1
(
Emp_Id INTEGER,
Pro_Id INTEGER
);


INSERT INTO Student1 VALUES ( 16,'RIDHIMA');
INSERT INTO Student1 VALUES ( 17,'ARMAN');
INSERT INTO Student1 VALUES ( 18,'ISHAN');
INSERT INTO Student1 VALUES ( 19,'SPARSH');
INSERT INTO Student1 VALUES ( 20,'MANIKA');
INSERT INTO Student1 VALUES ( 21,'GAURANG');
INSERT INTO Student1 VALUES ( 22,'SUBHASH');

INSERT INTO Library1 VALUES ( 100,16,'AM 4');
INSERT INTO Library1 VALUES ( 101,18,'AP 2');
INSERT INTO Library1 VALUES ( 102,20, 'oops');
INSERT INTO Library1 VALUES ( 103,27,'comm. system');
INSERT INTO Library1 VALUES ( 104,25,'c++');

SELECT * FROM Student1;

SELECT * FROM Library1;

SELECT Student1.S_Id, Student1.S_Name, Library1.B_Name 
FROM Student1 INNER JOIN Library1 
ON Student1.S_Id = Library1.S_Id;

SELECT Student1.S_Id, Student1.S_Name, Library1.B_Name 
FROM Student1 FULL OUTER JOIN Library1 
ON Student1.S_Id = Library1.S_Id;

INSERT INTO Emp1 VALUES (11, 'John','LAXMI NAGAR ','09-JUN-89','WEB');
INSERT INTO Emp1 VALUES (12, 'Nrg',' PITAMPURA','05-AUG-88','WEB');
INSERT INTO Emp1 VALUES (13, 'Tia','MOTI NAGAR ','09-Sep-87','ML');
INSERT INTO Emp1 VALUES (14, 'Ruhi','SHASTRI NAGAR ','04-JAN-91','AND');
INSERT INTO Emp1 VALUES (15, 'Kshvi','MEGHA NAGAR ','09-FEb-83','WEB');
INSERT INTO Emp1 VALUES (16, 'Ridhmima','SUMAN NAGAR ','08-JAN-84','ML');

INSERT INTO Project1 VALUES (21, 'bank','29-JUN-21','03-AUG-21');
INSERT INTO Project1 VALUES (22, 'agriculture','21-JAN-21','04-SEP-21');
INSERT INTO Project1 VALUES (23, 'property','22-FEB-21','05-AUG-21');
INSERT INTO Project1 VALUES (24, 'development','23-JUN-21','06-SEP-21');
INSERT INTO Project1 VALUES (25, 'bank','24-JAN-21','07-AUG-21');
INSERT INTO Project1 VALUES (26, 'bank','25-AUG-21','08-SEP-21');

INSERT INTO Assign1 VALUES (11,21);
INSERT INTO Assign1 VALUES (12,22);
INSERT INTO Assign1 VALUES (13,23 );
INSERT INTO Assign1 VALUES (14,24 );
INSERT INTO Assign1 VALUES (15,25 );
INSERT INTO Assign1 VALUES (16,26 );

SELECT * FROM Emp1;

SELECT * FROM Project1;

SELECT * FROM Assign1;

SELECT * 
FROM ((Emp1 E INNER JOIN Assign1 A ON E.Emp_Id = A.Emp_Id) 
INNER JOIN Project1 P ON A.Pro_Id = P.Pro_Id);