DROP TABLE Emp;

CREATE TABLE Emp
(
EmpN0 INTEGER,
EmpName VARCHAR2(20),
Sal NUMBER(8,2),
DeptNo INTEGER
);

INSERT INTO Emp VALUES (11, 'John', 8500, 10);
INSERT INTO Emp VALUES (12, 'Nrg', 8500, 20);
INSERT INTO Emp VALUES (13, 'Tia', 15000, 30);
INSERT INTO Emp VALUES (14, 'Ruhi', 16725, 20);
INSERT INTO Emp VALUES (15, 'Kshvi', 20045, 10);
INSERT INTO Emp VALUES (16, 'Ridhmima', 40052, 30);
INSERT INTO Emp VALUES (17, 'Armaan', 6000, 30);
INSERT INTO Emp VALUES (18, 'Ishaan', 8000, 20);
INSERT INTO Emp VALUES (19, 'Manika', 9000, 10);
INSERT INTO Emp VALUES (20, 'Subhash', 4000, 10);

SELECT * FROM Emp;

SELECT MAX(Sal) FROM Emp;
SELECT MIN(Sal) FROM Emp;
SELECT SUM(Sal) FROM Emp;
SELECT AVG(Sal) FROM Emp;
SELECT COUNT(Sal) FROM Emp;

SELECT * FROM Emp WHERE EmpName LIKE 'A%';
SELECT * FROM Emp WHERE EmpName LIKE '1_a%';
SELECT * FROM Emp WHERE EmpName LIKE '___';
SELECT * FROM Emp WHERE EmpName LIKE '____';
SELECT * FROM Emp WHERE EmpName LIKE '_____';