DROP TABLE Emp;

DROP TABLE Emp_Sal;

DROP TRIGGER Alpha;

CREATE TABLE Emp
(
Emp_Id INTEGER,
Emp_Name VARCHAR2(20),
Sal NUMERIC(8,2)
);

CREATE TABLE Emp_Sal
(
Emp_Id INTEGER,
New_Sal NUMERIC(8,2),
Message VARCHAR2(20)
);

INSERT INTO Emp VALUES(001, 'A', 50000.00);
INSERT INTO Emp VALUES(002, 'B', 40000.00);
INSERT INTO Emp VALUES(003, 'C', 30000.00);
INSERT INTO Emp VALUES(004, 'D', 60000.00);
INSERT INTO Emp VALUES(005, 'E', 70000.00);
INSERT INTO Emp VALUES(006, 'F', 80000.00);

SELECT * FROM Emp;

SELECT * FROM Emp_Sal;

CREATE TRIGGER Alpha
AFTER UPDATE OF Sal ON Emp
FOR EACH ROW
BEGIN
INSERT INTO Emp_Sal VALUES (:OLD.Emp_Id, :NEW.Sal, 'Updated Salary');
END;

UPDATE Emp 
SET Sal = 25000
WHERE Emp_Id = 002;

SELECT * FROM Emp;

SELECT * FROM Emp_Sal;
